import { Project, User, Technology, Activity } from "../types";

// Demo Users
export const demoUsers: User[] = [
  {
    id: "1",
    name: "Marco Rossi",
    email: "marco@company.com",
    role: "ceo",
    department: "Management",
  },
  {
    id: "2",
    name: "Laura Bianchi",
    email: "laura@company.com",
    role: "project-manager",
    department: "PMO",
  },
  {
    id: "3",
    name: "Alessandro Verdi",
    email: "alex@company.com",
    role: "developer",
    department: "Engineering",
  },
  {
    id: "4",
    name: "Giulia Ferrari",
    email: "giulia@company.com",
    role: "designer",
    department: "Design",
  },
  {
    id: "5",
    name: "Francesco Russo",
    email: "francesco@company.com",
    role: "developer",
    department: "Engineering",
  },
  {
    id: "6",
    name: "Sofia Colombo",
    email: "sofia@company.com",
    role: "qa",
    department: "Quality",
  },
  {
    id: "7",
    name: "Luca Martini",
    email: "luca@company.com",
    role: "devops",
    department: "Infrastructure",
  },
  {
    id: "8",
    name: "Elena Ricci",
    email: "elena@company.com",
    role: "developer",
    department: "Engineering",
  },
];

export const defaultTechnologies: Technology[] = [
  { id: "1", name: "React", category: "frontend", color: "#61DAFB" },
  { id: "2", name: "Next.js", category: "frontend", color: "#000000" },
  { id: "3", name: "Vue.js", category: "frontend", color: "#4FC08D" },
  { id: "4", name: "Angular", category: "frontend", color: "#DD0031" },
  { id: "5", name: "TypeScript", category: "frontend", color: "#3178C6" },
  { id: "6", name: "Node.js", category: "backend", color: "#339933" },
  { id: "7", name: "Python", category: "backend", color: "#3776AB" },
  { id: "8", name: "Java", category: "backend", color: "#ED8B00" },
  { id: "9", name: "Go", category: "backend", color: "#00ADD8" },
  { id: "10", name: "PostgreSQL", category: "database", color: "#4169E1" },
  { id: "11", name: "MongoDB", category: "database", color: "#47A248" },
  { id: "12", name: "Redis", category: "database", color: "#DC382D" },
  { id: "13", name: "Docker", category: "devops", color: "#2496ED" },
  { id: "14", name: "Kubernetes", category: "devops", color: "#326CE5" },
  { id: "15", name: "AWS", category: "devops", color: "#FF9900" },
  { id: "16", name: "Figma", category: "design", color: "#F24E1E" },
  { id: "17", name: "Swift", category: "frontend", color: "#F05138" },
  { id: "18", name: "Kotlin", category: "frontend", color: "#7F52FF" },
  { id: "19", name: "Flutter", category: "frontend", color: "#02569B" },
  { id: "20", name: "React Native", category: "frontend", color: "#61DAFB" },
  { id: "21", name: ".NET", category: "backend", color: "#512BD4" },
  { id: "22", name: "GraphQL", category: "backend", color: "#E10098" },
  { id: "23", name: "MySQL", category: "database", color: "#4479A1" },
  { id: "24", name: "Azure", category: "devops", color: "#0078D4" },
];

// Demo Projects
export const demoProjects: Project[] = [
  // PROJECT 1 - E-commerce Platform (in progress, molto completo)
  {
    id: "proj-001",
    name: "E-Commerce Platform v2.0",
    description:
      "Piattaforma e-commerce completa con gestione prodotti, carrello, pagamenti Stripe e dashboard admin. Migrazione dalla v1 con nuova architettura microservizi.",
    type: "fullstack",
    status: "in-progress",
    priority: "high",
    technologies: [
      { id: "2", name: "Next.js", category: "frontend", color: "#000000" },
      { id: "5", name: "TypeScript", category: "frontend", color: "#3178C6" },
      { id: "6", name: "Node.js", category: "backend", color: "#339933" },
      { id: "10", name: "PostgreSQL", category: "database", color: "#4169E1" },
      { id: "12", name: "Redis", category: "database", color: "#DC382D" },
      { id: "13", name: "Docker", category: "devops", color: "#2496ED" },
      { id: "15", name: "AWS", category: "devops", color: "#FF9900" },
    ],
    team: [demoUsers[1], demoUsers[2], demoUsers[3], demoUsers[4], demoUsers[5]],
    startDate: "2024-09-01",
    endDate: "2025-03-31",
    client: "TechRetail S.p.A.",
    repository: "https://github.com/company/ecommerce-v2",
    figmaLink: "https://figma.com/file/ecommerce-v2",
    createdAt: "2024-08-15T10:00:00Z",
    tags: [], updatedAt: "2024-12-02T15:30:00Z",
    tasks: [
      {
        id: "task-001",
        title: "Setup progetto Next.js 14 con App Router",
        description: "Configurare il progetto base con TypeScript, ESLint, Prettier e Tailwind CSS",
        status: "done",
        priority: "high",
        assignee: demoUsers[2],
        dueDate: "2024-09-10",
        createdAt: "2024-09-01T09:00:00Z",
        tags: [], updatedAt: "2024-09-08T16:00:00Z",
      },
      {
        id: "task-002",
        title: "Design sistema componenti UI",
        description: "Creare design system con Figma: bottoni, form, card, modal, navigation",
        status: "done",
        priority: "high",
        assignee: demoUsers[3],
        dueDate: "2024-09-20",
        createdAt: "2024-09-05T10:00:00Z",
        tags: [], updatedAt: "2024-09-18T14:00:00Z",
      },
      {
        id: "task-003",
        title: "Implementazione catalogo prodotti",
        description: "Pagina catalogo con filtri, ricerca full-text, paginazione e ordinamento",
        status: "done",
        priority: "high",
        assignee: demoUsers[4],
        dueDate: "2024-10-15",
        createdAt: "2024-09-20T09:00:00Z",
        tags: [], updatedAt: "2024-10-12T17:00:00Z",
      },
      {
        id: "task-004",
        title: "Sistema carrello e checkout",
        description: "Gestione carrello persistente, calcolo spedizioni, applicazione coupon",
        status: "in-progress",
        priority: "high",
        assignee: demoUsers[2],
        dueDate: "2024-12-10",
        createdAt: "2024-10-15T09:00:00Z",
        tags: [], updatedAt: "2024-12-01T11:00:00Z",
      },
      {
        id: "task-005",
        title: "Integrazione pagamenti Stripe",
        description: "Implementare Stripe Checkout, gestione webhook, retry pagamenti falliti",
        status: "in-progress",
        priority: "urgent",
        assignee: demoUsers[4],
        dueDate: "2024-12-15",
        createdAt: "2024-11-01T09:00:00Z",
        tags: [], updatedAt: "2024-12-02T09:00:00Z",
      },
      {
        id: "task-006",
        title: "Dashboard amministratore",
        description: "Pannello admin per gestione ordini, prodotti, utenti e analytics",
        status: "todo",
        priority: "medium",
        assignee: demoUsers[2],
        dueDate: "2025-01-15",
        createdAt: "2024-11-15T09:00:00Z",
        tags: [], updatedAt: "2024-11-15T09:00:00Z",
      },
      {
        id: "task-007",
        title: "Sistema notifiche email",
        description: "Template email transazionali con SendGrid: conferma ordine, spedizione, etc.",
        status: "todo",
        priority: "medium",
        assignee: demoUsers[4],
        dueDate: "2025-01-20",
        createdAt: "2024-11-20T09:00:00Z",
        tags: [], updatedAt: "2024-11-20T09:00:00Z",
      },
      {
        id: "task-008",
        title: "Test E2E con Playwright",
        description: "Suite completa di test end-to-end per flusso acquisto",
        status: "review",
        priority: "high",
        assignee: demoUsers[5],
        dueDate: "2024-12-20",
        createdAt: "2024-11-25T09:00:00Z",
        tags: [], updatedAt: "2024-12-01T14:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-001",
        content: "🚀 Kickoff meeting completato! Abbiamo definito l'architettura e le milestone principali. Prossimo step: setup ambiente di sviluppo.",
        author: demoUsers[1],
        createdAt: "2024-09-01T11:00:00Z",
        isAnnouncement: true,
      },
      {
        id: "msg-002",
        content: "Ho completato il design system su Figma. Trovate tutto organizzato per componenti. @Alessandro puoi iniziare con l'implementazione dei componenti base.",
        author: demoUsers[3],
        createdAt: "2024-09-18T15:00:00Z",
        mentions: ["3"],
      },
      {
        id: "msg-003",
        content: "Ottimo lavoro Giulia! I componenti sono chiarissimi. Inizio subito con Button, Input e Card.",
        author: demoUsers[2],
        createdAt: "2024-09-18T15:30:00Z",
      },
      {
        id: "msg-004",
        content: "⚠️ ATTENZIONE: Stripe ha rilasciato una nuova versione dell'SDK. Dobbiamo aggiornare prima del go-live. @Francesco puoi verificare la compatibilità?",
        author: demoUsers[1],
        createdAt: "2024-11-28T10:00:00Z",
        isAnnouncement: true,
        mentions: ["5"],
      },
      {
        id: "msg-005",
        content: "Ho verificato, la nuova versione è retrocompatibile. Aggiorno le dipendenze oggi.",
        author: demoUsers[4],
        createdAt: "2024-11-28T11:30:00Z",
      },
      {
        id: "msg-006",
        content: "I test E2E sono quasi completi. Ho trovato un bug nel flusso di checkout quando si applica un coupon scaduto. Apro un defect.",
        author: demoUsers[5],
        createdAt: "2024-12-01T16:00:00Z",
      },
    ],
    milestones: [
      {
        id: "ms-001",
        title: "MVP - Catalogo e Carrello",
        description: "Rilascio della prima versione con catalogo prodotti funzionante e carrello base",
        dueDate: "2024-11-30",
        status: "completed",
        progress: 100,
      },
      {
        id: "ms-002",
        title: "Beta - Pagamenti e Checkout",
        description: "Integrazione completa dei pagamenti e flusso checkout ottimizzato",
        dueDate: "2024-12-31",
        status: "in-progress",
        progress: 65,
      },
      {
        id: "ms-003",
        title: "Release - Admin Dashboard",
        description: "Dashboard amministrativa completa con analytics e gestione ordini",
        dueDate: "2025-02-15",
        status: "pending",
        progress: 10,
      },
      {
        id: "ms-004",
        title: "Go-Live Production",
        description: "Lancio in produzione con migrazione dati dalla v1",
        dueDate: "2025-03-31",
        status: "pending",
        progress: 0,
      },
    ],
    functionalAnalyses: [
      {
        id: "fa-001",
        projectId: "proj-001",
        title: "Analisi Funzionale - Modulo E-Commerce",
        version: "2.1",
        status: "approved",
        description: "Documento di analisi funzionale completo per la piattaforma e-commerce v2.0",
        scope: "Gestione catalogo, carrello, checkout, pagamenti, account utente, dashboard admin",
        outOfScope: "App mobile nativa, marketplace multi-vendor, sistema affiliazione",
        assumptions: [
          "Integrazione con Stripe come unico gateway di pagamento",
          "Spedizioni gestite tramite API corrieri esterni",
          "Massimo 10.000 prodotti nel catalogo iniziale",
        ],
        constraints: [
          "GDPR compliance obbligatorio",
          "Performance: pagine < 3s load time",
          "Supporto browser: ultimi 2 anni",
        ],
        requirements: [
          {
            id: "req-001",
            code: "REQ-001",
            title: "Registrazione Utente",
            description: "L'utente deve poter registrarsi con email/password o tramite social login (Google, Facebook)",
            type: "functional",
            priority: "must-have",
            status: "implemented",
            acceptanceCriteria: [
              "Form registrazione con validazione email",
              "Password minimo 8 caratteri con maiuscola e numero",
              "Email di conferma inviata entro 30 secondi",
              "Social login funzionante con Google e Facebook",
            ],
            dependencies: [],
            author: demoUsers[1],
            reviewer: demoUsers[2],
            createdAt: "2024-09-05T10:00:00Z",
            tags: [], updatedAt: "2024-10-20T14:00:00Z",
            approvedAt: "2024-09-15T11:00:00Z",
            approvedBy: demoUsers[0],
            comments: [],
            attachments: [],
            linkedTasks: ["task-001"],
            version: 1,
            history: [],
          },
          {
            id: "req-002",
            code: "REQ-002",
            title: "Catalogo Prodotti con Filtri",
            description: "Visualizzazione catalogo con ricerca full-text, filtri per categoria/prezzo/brand e ordinamento",
            type: "functional",
            priority: "must-have",
            status: "implemented",
            acceptanceCriteria: [
              "Ricerca con autocomplete",
              "Filtri multipli combinabili",
              "Risultati paginati (24 per pagina)",
              "Ordinamento per prezzo, popolarità, novità",
            ],
            dependencies: [],
            author: demoUsers[1],
            reviewer: demoUsers[2],
            createdAt: "2024-09-05T10:30:00Z",
            tags: [], updatedAt: "2024-10-25T16:00:00Z",
            approvedAt: "2024-09-15T11:30:00Z",
            approvedBy: demoUsers[0],
            comments: [],
            attachments: [],
            linkedTasks: ["task-003"],
            version: 2,
            history: [],
          },
          {
            id: "req-003",
            code: "REQ-003",
            title: "Carrello Persistente",
            description: "Il carrello deve persistere tra sessioni per utenti loggati e salvare in localStorage per guest",
            type: "functional",
            priority: "must-have",
            status: "approved",
            acceptanceCriteria: [
              "Carrello salvato su database per utenti registrati",
              "Carrello in localStorage per guest",
              "Merge carrello guest al login",
              "Notifica prodotto esaurito nel carrello",
            ],
            dependencies: ["req-001"],
            author: demoUsers[1],
            reviewer: demoUsers[2],
            createdAt: "2024-09-06T09:00:00Z",
            tags: [], updatedAt: "2024-09-20T10:00:00Z",
            approvedAt: "2024-09-20T10:00:00Z",
            approvedBy: demoUsers[0],
            comments: [],
            attachments: [],
            linkedTasks: ["task-004"],
            version: 1,
            history: [],
          },
          {
            id: "req-004",
            code: "REQ-004",
            title: "Checkout Multi-step",
            description: "Processo di checkout guidato: indirizzo > spedizione > pagamento > conferma",
            type: "functional",
            priority: "must-have",
            status: "review",
            acceptanceCriteria: [
              "Step chiari con progress indicator",
              "Validazione inline per ogni campo",
              "Salvataggio indirizzi per utenti registrati",
              "Riepilogo ordine sempre visibile",
            ],
            dependencies: ["req-003"],
            author: demoUsers[1],
            createdAt: "2024-09-06T10:00:00Z",
            tags: [], updatedAt: "2024-11-30T14:00:00Z",
            comments: [],
            attachments: [],
            linkedTasks: ["task-004"],
            version: 1,
            history: [],
          },
          {
            id: "req-005",
            code: "REQ-005",
            title: "Performance sotto carico",
            description: "Il sistema deve supportare almeno 1000 utenti concorrenti senza degradazione",
            type: "non-functional",
            priority: "must-have",
            status: "draft",
            acceptanceCriteria: [
              "Response time p95 < 500ms",
              "Zero downtime durante deploy",
              "Auto-scaling su AWS",
              "Cache layer con Redis",
            ],
            dependencies: [],
            author: demoUsers[6],
            createdAt: "2024-09-10T09:00:00Z",
            tags: [], updatedAt: "2024-09-10T09:00:00Z",
            comments: [],
            attachments: [],
            linkedTasks: [],
            version: 1,
            history: [],
          },
        ],
        createdAt: "2024-09-05T09:00:00Z",
        tags: [], updatedAt: "2024-11-30T15:00:00Z",
        createdBy: demoUsers[1],
        approvedBy: demoUsers[0],
        approvedAt: "2024-09-25T10:00:00Z",
      },
    ],
    estimations: [
      {
        id: "est-001",
        projectId: "proj-001",
        title: "Stima Effort - Sprint 1-4",
        version: "1.2",
        status: "approved",
        description: "Stima dettagliata per i primi 4 sprint del progetto e-commerce",
        bufferPercentage: 20,
        totalHours: 520,
        items: [
          {
            id: "ei-001",
            title: "Setup infrastruttura AWS",
            description: "VPC, ECS, RDS, ElastiCache, S3, CloudFront",
            category: "devops",
            estimatedHours: 40,
            complexity: "high",
            confidence: "high",
          },
          {
            id: "ei-002",
            title: "Design System implementazione",
            description: "Tutti i componenti UI del design system Figma",
            category: "development",
            estimatedHours: 80,
            complexity: "medium",
            confidence: "high",
          },
          {
            id: "ei-003",
            title: "API Catalogo Prodotti",
            description: "CRUD prodotti, varianti, immagini, categorie, tag",
            category: "development",
            estimatedHours: 60,
            complexity: "medium",
            confidence: "high",
          },
          {
            id: "ei-004",
            title: "Frontend Catalogo",
            description: "Pagine lista, dettaglio, filtri, ricerca",
            category: "development",
            estimatedHours: 80,
            complexity: "medium",
            confidence: "medium",
          },
          {
            id: "ei-005",
            title: "Sistema Carrello",
            description: "Backend e frontend gestione carrello",
            category: "development",
            estimatedHours: 50,
            complexity: "medium",
            confidence: "high",
          },
          {
            id: "ei-006",
            title: "Integrazione Stripe",
            description: "Checkout, webhook, gestione errori",
            category: "development",
            estimatedHours: 40,
            complexity: "high",
            confidence: "medium",
          },
          {
            id: "ei-007",
            title: "UI/UX Review e Iterazioni",
            description: "Review design, A/B test, ottimizzazioni",
            category: "design",
            estimatedHours: 40,
            complexity: "low",
            confidence: "medium",
          },
          {
            id: "ei-008",
            title: "Test Suite",
            description: "Unit test, integration test, E2E",
            category: "testing",
            estimatedHours: 80,
            complexity: "medium",
            confidence: "medium",
          },
          {
            id: "ei-009",
            title: "Documentazione",
            description: "API docs, README, guide deploy",
            category: "documentation",
            estimatedHours: 30,
            complexity: "low",
            confidence: "high",
          },
          {
            id: "ei-010",
            title: "Project Management",
            description: "Planning, daily, review, retro",
            category: "management",
            estimatedHours: 20,
            complexity: "low",
            confidence: "high",
          },
        ],
        createdAt: "2024-09-10T10:00:00Z",
        tags: [], updatedAt: "2024-09-20T14:00:00Z",
        createdBy: demoUsers[1],
        approvedBy: demoUsers[0],
        approvedAt: "2024-09-22T10:00:00Z",
      },
    ],
    testCases: [
      {
        id: "tc-001",
        code: "TC-001",
        title: "Login utente con credenziali valide",
        description: "Verificare che un utente registrato possa effettuare il login",
        type: "manual",
        priority: "critical",
        status: "active",
        preconditions: "Utente già registrato con email test@example.com",
        steps: [
          { id: "s1", stepNumber: 1, action: "Aprire la pagina di login", expectedResult: "Pagina login visualizzata correttamente" },
          { id: "s2", stepNumber: 2, action: "Inserire email: test@example.com", expectedResult: "Email accettata" },
          { id: "s3", stepNumber: 3, action: "Inserire password valida", expectedResult: "Password mascherata" },
          { id: "s4", stepNumber: 4, action: "Cliccare su 'Accedi'", expectedResult: "Redirect a dashboard utente" },
        ],
        tags: ["login", "auth", "critical-path"],
        estimatedDuration: 5,
        createdAt: "2024-10-01T09:00:00Z",
        tags: [], updatedAt: "2024-10-01T09:00:00Z",
        author: demoUsers[5],
      },
      {
        id: "tc-002",
        code: "TC-002",
        title: "Aggiunta prodotto al carrello",
        description: "Verificare che un prodotto possa essere aggiunto al carrello dalla pagina dettaglio",
        type: "manual",
        priority: "critical",
        status: "active",
        preconditions: "Almeno un prodotto disponibile nel catalogo",
        steps: [
          { id: "s1", stepNumber: 1, action: "Navigare al catalogo prodotti", expectedResult: "Lista prodotti visualizzata" },
          { id: "s2", stepNumber: 2, action: "Cliccare su un prodotto", expectedResult: "Pagina dettaglio prodotto" },
          { id: "s3", stepNumber: 3, action: "Selezionare quantità: 2", expectedResult: "Quantità aggiornata a 2" },
          { id: "s4", stepNumber: 4, action: "Cliccare 'Aggiungi al carrello'", expectedResult: "Toast conferma, badge carrello +2" },
          { id: "s5", stepNumber: 5, action: "Aprire il carrello", expectedResult: "Prodotto presente con quantità 2" },
        ],
        tags: ["cart", "critical-path"],
        estimatedDuration: 8,
        createdAt: "2024-10-01T10:00:00Z",
        tags: [], updatedAt: "2024-10-01T10:00:00Z",
        author: demoUsers[5],
      },
      {
        id: "tc-003",
        code: "TC-003",
        title: "Checkout con carta di credito",
        description: "Verificare il flusso completo di checkout con pagamento carta",
        type: "manual",
        priority: "critical",
        status: "active",
        preconditions: "Utente loggato con prodotti nel carrello",
        steps: [
          { id: "s1", stepNumber: 1, action: "Andare al checkout", expectedResult: "Step indirizzo visualizzato" },
          { id: "s2", stepNumber: 2, action: "Compilare indirizzo spedizione", expectedResult: "Validazione OK, avanti abilitato" },
          { id: "s3", stepNumber: 3, action: "Selezionare spedizione standard", expectedResult: "Costo spedizione aggiunto" },
          { id: "s4", stepNumber: 4, action: "Inserire carta test Stripe", expectedResult: "Carta validata" },
          { id: "s5", stepNumber: 5, action: "Confermare ordine", expectedResult: "Pagina conferma con numero ordine" },
        ],
        linkedRequirement: "req-004",
        tags: ["checkout", "payment", "critical-path"],
        estimatedDuration: 15,
        createdAt: "2024-10-05T09:00:00Z",
        tags: [], updatedAt: "2024-11-20T14:00:00Z",
        author: demoUsers[5],
      },
      {
        id: "tc-004",
        code: "TC-004",
        title: "Ricerca prodotti con filtri",
        description: "Verificare la funzionalità di ricerca con filtri combinati",
        type: "manual",
        priority: "high",
        status: "active",
        steps: [
          { id: "s1", stepNumber: 1, action: "Cercare 'smartphone'", expectedResult: "Risultati filtrati per keyword" },
          { id: "s2", stepNumber: 2, action: "Applicare filtro prezzo 200-500€", expectedResult: "Solo prodotti in range" },
          { id: "s3", stepNumber: 3, action: "Applicare filtro brand 'Samsung'", expectedResult: "Filtri combinati applicati" },
          { id: "s4", stepNumber: 4, action: "Ordinare per prezzo crescente", expectedResult: "Prodotti ordinati correttamente" },
        ],
        linkedRequirement: "req-002",
        tags: ["search", "catalog"],
        estimatedDuration: 10,
        createdAt: "2024-10-05T10:00:00Z",
        tags: [], updatedAt: "2024-10-05T10:00:00Z",
        author: demoUsers[5],
      },
    ],
    testCycles: [
      {
        id: "cycle-001",
        projectId: "proj-001",
        name: "Regression Test - Sprint 4",
        description: "Test di regressione completo prima del rilascio beta",
        environment: "Staging",
        version: "2.0.0-beta.1",
        status: "in-progress",
        startDate: "2024-12-01",
        endDate: "2024-12-10",
        testCases: [],
        executions: [
          {
            id: "exec-001",
            testCaseId: "tc-001",
            testCase: {} as any,
            executedBy: demoUsers[5],
            executedAt: "2024-12-02T10:00:00Z",
            result: "passed",
            duration: 4,
            environment: "Staging",
            browser: "Chrome 120",
          },
          {
            id: "exec-002",
            testCaseId: "tc-002",
            testCase: {} as any,
            executedBy: demoUsers[5],
            executedAt: "2024-12-02T10:30:00Z",
            result: "passed",
            duration: 7,
            environment: "Staging",
            browser: "Chrome 120",
          },
          {
            id: "exec-003",
            testCaseId: "tc-003",
            testCase: {} as any,
            executedBy: demoUsers[5],
            executedAt: "2024-12-02T11:00:00Z",
            result: "failed",
            duration: 12,
            environment: "Staging",
            browser: "Chrome 120",
            notes: "Errore nel calcolo sconto con coupon scaduto",
            defects: ["def-001"],
          },
        ],
        createdAt: "2024-12-01T09:00:00Z",
        createdBy: demoUsers[5],
        summary: {
          total: 4,
          passed: 2,
          failed: 1,
          blocked: 0,
          skipped: 0,
          notRun: 1,
          passRate: 66.7,
          executionProgress: 75,
        },
      },
    ],
    defects: [
      {
        id: "def-001",
        code: "BUG-001",
        title: "Errore calcolo sconto con coupon scaduto",
        description: "Quando si applica un coupon scaduto, il sistema mostra un errore 500 invece di un messaggio user-friendly",
        severity: "high",
        priority: "high",
        status: "open",
        stepsToReproduce: [
          "Aggiungere prodotti al carrello",
          "Andare al checkout",
          "Inserire codice coupon SCADUTO2023",
          "Cliccare Applica",
        ],
        expectedBehavior: "Messaggio 'Coupon scaduto o non valido' con codice rimosso",
        actualBehavior: "Errore 500, pagina bianca, carrello svuotato",
        environment: "Staging",
        browser: "Chrome 120",
        reportedBy: demoUsers[5],
        assignedTo: demoUsers[4],
        linkedTestCase: "tc-003",
        attachments: [],
        createdAt: "2024-12-02T11:30:00Z",
        tags: [], updatedAt: "2024-12-02T14:00:00Z",
      },
      {
        id: "def-002",
        code: "BUG-002",
        title: "Immagini prodotto non si caricano su Safari mobile",
        description: "Le immagini lazy-loaded non vengono visualizzate su Safari iOS 17",
        severity: "medium",
        priority: "medium",
        status: "in-progress",
        stepsToReproduce: [
          "Aprire il catalogo su iPhone con Safari",
          "Scrollare la lista prodotti",
          "Osservare le immagini",
        ],
        expectedBehavior: "Immagini caricate progressivamente durante lo scroll",
        actualBehavior: "Placeholder grigio rimane, immagini non caricate",
        environment: "Production",
        browser: "Safari 17",
        device: "iPhone 15 Pro",
        reportedBy: demoUsers[3],
        assignedTo: demoUsers[2],
        attachments: [],
        createdAt: "2024-11-28T09:00:00Z",
        tags: [], updatedAt: "2024-12-01T16:00:00Z",
      },
    ],
    timeEntries: [],
  },

  // PROJECT 2 - App Mobile Banking (completato)
  {
    id: "proj-002",
    name: "Mobile Banking App",
    description: "Applicazione mobile per servizi bancari: consultazione saldo, bonifici, pagamenti, gestione carte. iOS e Android con Flutter.",
    type: "mobile",
    status: "completed",
    priority: "urgent",
    technologies: [
      { id: "19", name: "Flutter", category: "frontend", color: "#02569B" },
      { id: "8", name: "Java", category: "backend", color: "#ED8B00" },
      { id: "10", name: "PostgreSQL", category: "database", color: "#4169E1" },
      { id: "14", name: "Kubernetes", category: "devops", color: "#326CE5" },
    ],
    team: [demoUsers[1], demoUsers[4], demoUsers[5], demoUsers[6]],
    startDate: "2024-03-01",
    endDate: "2024-10-31",
    client: "Banca Innovativa S.p.A.",
    createdAt: "2024-02-15T10:00:00Z",
    tags: [], updatedAt: "2024-11-05T09:00:00Z",
    tasks: [
      {
        id: "task-101",
        title: "Autenticazione biometrica",
        description: "Implementare login con Face ID/Touch ID e fingerprint Android",
        status: "done",
        priority: "urgent",
        assignee: demoUsers[4],
        dueDate: "2024-04-30",
        createdAt: "2024-03-01T09:00:00Z",
        tags: [], updatedAt: "2024-04-25T16:00:00Z",
      },
      {
        id: "task-102",
        title: "Dashboard saldo e movimenti",
        description: "Schermata principale con saldo, ultimi movimenti e grafici spese",
        status: "done",
        priority: "high",
        assignee: demoUsers[4],
        dueDate: "2024-05-15",
        createdAt: "2024-04-01T09:00:00Z",
        tags: [], updatedAt: "2024-05-10T14:00:00Z",
      },
      {
        id: "task-103",
        title: "Bonifici SEPA",
        description: "Funzionalità bonifico con rubrica beneficiari e bonifici ricorrenti",
        status: "done",
        priority: "high",
        assignee: demoUsers[4],
        dueDate: "2024-06-30",
        createdAt: "2024-05-01T09:00:00Z",
        tags: [], updatedAt: "2024-06-28T17:00:00Z",
      },
      {
        id: "task-104",
        title: "Push notifications",
        description: "Notifiche in tempo reale per transazioni e alert sicurezza",
        status: "done",
        priority: "medium",
        assignee: demoUsers[6],
        dueDate: "2024-07-31",
        createdAt: "2024-06-15T09:00:00Z",
        tags: [], updatedAt: "2024-07-28T15:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-101",
        content: "🎉 App rilasciata su App Store e Play Store! Ottime recensioni, 4.8 stelle!",
        author: demoUsers[1],
        createdAt: "2024-11-01T10:00:00Z",
        isAnnouncement: true,
      },
      {
        id: "msg-102",
        content: "Complimenti a tutto il team! 7 mesi di lavoro intenso ma il risultato è eccezionale.",
        author: demoUsers[0],
        createdAt: "2024-11-01T11:00:00Z",
      },
    ],
    milestones: [
      {
        id: "ms-101",
        title: "MVP Release",
        description: "Prima versione con funzionalità base",
        dueDate: "2024-06-30",
        status: "completed",
        progress: 100,
      },
      {
        id: "ms-102",
        title: "Beta Testing",
        description: "Test con 1000 utenti pilota",
        dueDate: "2024-09-30",
        status: "completed",
        progress: 100,
      },
      {
        id: "ms-103",
        title: "Public Release",
        description: "Rilascio pubblico su store",
        dueDate: "2024-10-31",
        status: "completed",
        progress: 100,
      },
    ],
    functionalAnalyses: [],
    estimations: [],
    testCases: [],
    testCycles: [],
    defects: [],
    timeEntries: [],
  },

  // PROJECT 3 - CRM Enterprise (in planning)
  {
    id: "proj-003",
    name: "CRM Enterprise Suite",
    description: "Sistema CRM completo per gestione clienti, lead, opportunità, preventivi e reportistica avanzata con AI.",
    type: "web",
    status: "planning",
    priority: "high",
    technologies: [
      { id: "1", name: "React", category: "frontend", color: "#61DAFB" },
      { id: "5", name: "TypeScript", category: "frontend", color: "#3178C6" },
      { id: "7", name: "Python", category: "backend", color: "#3776AB" },
      { id: "11", name: "MongoDB", category: "database", color: "#47A248" },
      { id: "24", name: "Azure", category: "devops", color: "#0078D4" },
    ],
    team: [demoUsers[1], demoUsers[2], demoUsers[7]],
    startDate: "2025-01-15",
    endDate: "2025-09-30",
    client: "Gruppo Vendite Italia",
    createdAt: "2024-11-20T10:00:00Z",
    tags: [], updatedAt: "2024-12-01T15:00:00Z",
    tasks: [
      {
        id: "task-201",
        title: "Definizione architettura",
        description: "Design architettura microservizi e scelta stack tecnologico",
        status: "in-progress",
        priority: "high",
        assignee: demoUsers[2],
        dueDate: "2024-12-20",
        createdAt: "2024-11-20T10:00:00Z",
        tags: [], updatedAt: "2024-12-01T10:00:00Z",
      },
      {
        id: "task-202",
        title: "Raccolta requisiti stakeholder",
        description: "Workshop con sales director e team vendite per requisiti funzionali",
        status: "review",
        priority: "high",
        assignee: demoUsers[1],
        dueDate: "2024-12-15",
        createdAt: "2024-11-20T11:00:00Z",
        tags: [], updatedAt: "2024-12-02T09:00:00Z",
      },
      {
        id: "task-203",
        title: "PoC integrazione AI",
        description: "Proof of concept per lead scoring automatico con ML",
        status: "todo",
        priority: "medium",
        assignee: demoUsers[7],
        dueDate: "2025-01-10",
        createdAt: "2024-11-25T10:00:00Z",
        tags: [], updatedAt: "2024-11-25T10:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-201",
        content: "Kickoff meeting schedulato per il 10 gennaio. Prepariamo la documentazione iniziale.",
        author: demoUsers[1],
        createdAt: "2024-11-20T14:00:00Z",
        isAnnouncement: true,
      },
    ],
    milestones: [
      {
        id: "ms-201",
        title: "Discovery Phase",
        description: "Raccolta requisiti e definizione scope",
        dueDate: "2025-02-28",
        status: "pending",
        progress: 25,
      },
      {
        id: "ms-202",
        title: "MVP Development",
        description: "Sviluppo funzionalità core",
        dueDate: "2025-06-30",
        status: "pending",
        progress: 0,
      },
    ],
    functionalAnalyses: [],
    estimations: [],
    testCases: [],
    testCycles: [],
    defects: [],
    timeEntries: [],
  },

  // PROJECT 4 - API Gateway (review)
  {
    id: "proj-004",
    name: "API Gateway & Authentication",
    description: "Gateway centralizzato per API con autenticazione OAuth2/OIDC, rate limiting, logging e monitoring.",
    type: "api",
    status: "review",
    priority: "high",
    technologies: [
      { id: "9", name: "Go", category: "backend", color: "#00ADD8" },
      { id: "12", name: "Redis", category: "database", color: "#DC382D" },
      { id: "14", name: "Kubernetes", category: "devops", color: "#326CE5" },
      { id: "13", name: "Docker", category: "devops", color: "#2496ED" },
    ],
    team: [demoUsers[1], demoUsers[4], demoUsers[6]],
    startDate: "2024-07-01",
    endDate: "2024-12-31",
    createdAt: "2024-06-15T10:00:00Z",
    tags: [], updatedAt: "2024-12-02T11:00:00Z",
    tasks: [
      {
        id: "task-301",
        title: "Core Gateway implementation",
        description: "Proxy reverso con routing dinamico e middleware chain",
        status: "done",
        priority: "high",
        assignee: demoUsers[4],
        dueDate: "2024-09-30",
        createdAt: "2024-07-01T09:00:00Z",
        tags: [], updatedAt: "2024-09-25T16:00:00Z",
      },
      {
        id: "task-302",
        title: "OAuth2 Authorization Server",
        description: "Implementazione completa flussi OAuth2: authorization code, client credentials, refresh",
        status: "done",
        priority: "urgent",
        assignee: demoUsers[4],
        dueDate: "2024-10-31",
        createdAt: "2024-08-01T09:00:00Z",
        tags: [], updatedAt: "2024-10-28T15:00:00Z",
      },
      {
        id: "task-303",
        title: "Rate limiting e throttling",
        description: "Limiti per IP, utente, API key con Redis sliding window",
        status: "review",
        priority: "high",
        assignee: demoUsers[4],
        dueDate: "2024-11-30",
        createdAt: "2024-10-01T09:00:00Z",
        tags: [], updatedAt: "2024-12-01T10:00:00Z",
      },
      {
        id: "task-304",
        title: "Documentazione OpenAPI",
        description: "Generazione automatica spec OpenAPI 3.1 da codice",
        status: "in-progress",
        priority: "medium",
        assignee: demoUsers[6],
        dueDate: "2024-12-15",
        createdAt: "2024-11-15T09:00:00Z",
        tags: [], updatedAt: "2024-12-02T09:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-301",
        content: "Il penetration test è stato completato con successo. Nessuna vulnerabilità critica trovata! 🛡️",
        author: demoUsers[6],
        createdAt: "2024-11-25T16:00:00Z",
        isAnnouncement: true,
      },
    ],
    milestones: [
      {
        id: "ms-301",
        title: "Security Audit",
        description: "Audit sicurezza e penetration test",
        dueDate: "2024-11-30",
        status: "completed",
        progress: 100,
      },
      {
        id: "ms-302",
        title: "Production Deployment",
        description: "Deploy in produzione e migrazione traffic",
        dueDate: "2024-12-31",
        status: "in-progress",
        progress: 60,
      },
    ],
    functionalAnalyses: [],
    estimations: [],
    testCases: [],
    testCycles: [],
    defects: [],
    timeEntries: [],
  },

  // PROJECT 5 - Design System (completato)
  {
    id: "proj-005",
    name: "Corporate Design System",
    description: "Design system aziendale unificato: component library React, Figma tokens, documentazione Storybook.",
    type: "web",
    status: "completed",
    priority: "medium",
    technologies: [
      { id: "1", name: "React", category: "frontend", color: "#61DAFB" },
      { id: "5", name: "TypeScript", category: "frontend", color: "#3178C6" },
      { id: "16", name: "Figma", category: "design", color: "#F24E1E" },
    ],
    team: [demoUsers[1], demoUsers[3], demoUsers[2]],
    startDate: "2024-04-01",
    endDate: "2024-08-31",
    createdAt: "2024-03-15T10:00:00Z",
    tags: [], updatedAt: "2024-09-05T14:00:00Z",
    tasks: [
      {
        id: "task-401",
        title: "Design tokens Figma",
        description: "Definizione colori, tipografia, spacing, shadows in Figma",
        status: "done",
        priority: "high",
        assignee: demoUsers[3],
        dueDate: "2024-05-15",
        createdAt: "2024-04-01T09:00:00Z",
        tags: [], updatedAt: "2024-05-12T16:00:00Z",
      },
      {
        id: "task-402",
        title: "Component library base",
        description: "Button, Input, Select, Checkbox, Radio, Modal, Toast",
        status: "done",
        priority: "high",
        assignee: demoUsers[2],
        dueDate: "2024-06-30",
        createdAt: "2024-05-01T09:00:00Z",
        tags: [], updatedAt: "2024-06-28T15:00:00Z",
      },
      {
        id: "task-403",
        title: "Storybook documentation",
        description: "Setup Storybook con documentazione interattiva e playground",
        status: "done",
        priority: "medium",
        assignee: demoUsers[2],
        dueDate: "2024-07-31",
        createdAt: "2024-06-15T09:00:00Z",
        tags: [], updatedAt: "2024-07-28T14:00:00Z",
      },
      {
        id: "task-404",
        title: "NPM package publishing",
        description: "Configurazione CI/CD per pubblicazione automatica su npm privato",
        status: "done",
        priority: "medium",
        assignee: demoUsers[6],
        dueDate: "2024-08-15",
        createdAt: "2024-07-15T09:00:00Z",
        tags: [], updatedAt: "2024-08-10T16:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-401",
        content: "Design System v1.0 pubblicato! Trovate tutto su storybook.company.internal e nel registry npm aziendale.",
        author: demoUsers[1],
        createdAt: "2024-09-01T10:00:00Z",
        isAnnouncement: true,
      },
      {
        id: "msg-402",
        content: "Ottimo lavoro team! Il CEO ha lodato il risultato nella town hall. 🎉",
        author: demoUsers[0],
        createdAt: "2024-09-02T09:00:00Z",
      },
    ],
    milestones: [
      {
        id: "ms-401",
        title: "v1.0 Release",
        description: "Prima release stabile del design system",
        dueDate: "2024-08-31",
        status: "completed",
        progress: 100,
      },
    ],
    functionalAnalyses: [],
    estimations: [],
    testCases: [],
    testCycles: [],
    defects: [],
    timeEntries: [],
  },

  // PROJECT 6 - Data Platform (on-hold)
  {
    id: "proj-006",
    name: "Data Analytics Platform",
    description: "Piattaforma di data analytics con data warehouse, ETL pipelines, dashboard real-time e machine learning.",
    type: "fullstack",
    status: "on-hold",
    priority: "medium",
    technologies: [
      { id: "7", name: "Python", category: "backend", color: "#3776AB" },
      { id: "10", name: "PostgreSQL", category: "database", color: "#4169E1" },
      { id: "15", name: "AWS", category: "devops", color: "#FF9900" },
    ],
    team: [demoUsers[1], demoUsers[7]],
    startDate: "2024-06-01",
    endDate: "2025-03-31",
    createdAt: "2024-05-15T10:00:00Z",
    tags: [], updatedAt: "2024-10-15T10:00:00Z",
    tasks: [
      {
        id: "task-501",
        title: "Data warehouse schema design",
        description: "Progettazione schema star/snowflake per DWH",
        status: "done",
        priority: "high",
        assignee: demoUsers[7],
        dueDate: "2024-07-31",
        createdAt: "2024-06-01T09:00:00Z",
        tags: [], updatedAt: "2024-07-25T16:00:00Z",
      },
      {
        id: "task-502",
        title: "ETL pipelines con Airflow",
        description: "Pipeline ETL per ingestion dati da CRM, ERP, e-commerce",
        status: "in-progress",
        priority: "high",
        assignee: demoUsers[7],
        dueDate: "2024-10-31",
        createdAt: "2024-07-15T09:00:00Z",
        tags: [], updatedAt: "2024-10-10T14:00:00Z",
      },
    ],
    messages: [
      {
        id: "msg-501",
        content: "⏸️ Progetto in pausa per priorità budget Q4. Riprenderemo a gennaio 2025.",
        author: demoUsers[1],
        createdAt: "2024-10-15T10:00:00Z",
        isAnnouncement: true,
      },
    ],
    milestones: [
      {
        id: "ms-501",
        title: "Data Warehouse Ready",
        description: "DWH operativo con dati storici migrati",
        dueDate: "2024-10-31",
        status: "in-progress",
        progress: 70,
      },
    ],
    functionalAnalyses: [],
    estimations: [],
    testCases: [],
    testCycles: [],
    defects: [],
    timeEntries: [],
  },
];

// Demo Activities
export const demoActivities: Activity[] = [
  {
    id: "act-001",
    projectId: "proj-001",
    userId: "5",
    action: "defect_create",
    details: "Creato bug BUG-001: Errore calcolo sconto con coupon scaduto",
    entityType: "defect",
    entityId: "def-001",
    createdAt: "2024-12-02T11:30:00Z",
  },
  {
    id: "act-002",
    projectId: "proj-001",
    userId: "6",
    action: "test_execute",
    details: "Eseguito test TC-003: Checkout con carta di credito - FAILED",
    entityType: "test",
    entityId: "tc-003",
    createdAt: "2024-12-02T11:00:00Z",
  },
  {
    id: "act-003",
    projectId: "proj-001",
    userId: "3",
    action: "task_update",
    details: "Task 'Sistema carrello e checkout' aggiornato: 80% completato",
    entityType: "task",
    entityId: "task-004",
    createdAt: "2024-12-01T16:00:00Z",
  },
  {
    id: "act-004",
    projectId: "proj-004",
    userId: "7",
    action: "milestone_complete",
    details: "Milestone 'Security Audit' completata",
    entityType: "project",
    entityId: "proj-004",
    createdAt: "2024-11-30T17:00:00Z",
  },
  {
    id: "act-005",
    projectId: "proj-003",
    userId: "2",
    action: "project_create",
    details: "Progetto 'CRM Enterprise Suite' creato",
    entityType: "project",
    entityId: "proj-003",
    createdAt: "2024-11-20T10:00:00Z",
  },
  {
    id: "act-006",
    projectId: "proj-001",
    userId: "2",
    action: "requirement_approve",
    details: "Requisito REQ-003 'Carrello Persistente' approvato",
    entityType: "requirement",
    entityId: "req-003",
    createdAt: "2024-09-20T10:00:00Z",
  },
  {
    id: "act-007",
    projectId: "proj-001",
    userId: "2",
    action: "estimation_approve",
    details: "Stima 'Sprint 1-4' approvata - 520 ore totali",
    entityType: "estimation",
    entityId: "est-001",
    createdAt: "2024-09-22T10:00:00Z",
  },
  {
    id: "act-008",
    projectId: "proj-002",
    userId: "2",
    action: "project_complete",
    details: "Progetto 'Mobile Banking App' completato con successo!",
    entityType: "project",
    entityId: "proj-002",
    createdAt: "2024-11-01T10:00:00Z",
  },
];
